void mostraMenu();
void visualizarLista();
void consultar_lista();
void esvaziar_lista();
void inserirCodigo();
int lista_esta_vazia();
int lista_esta_cheia();
void remove_elemento();
void qtd_elementos(int eh_menu);
void clear();